apiVersion: apps/v1
kind: Deployment
metadata:
  name: dusk-node
  namespace: dusk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dusk-node
  template:
    metadata:
      labels:
        app: dusk-node
    spec:
      containers:
        - name: dusk-node
          image: dusknetwork/node:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: api
            - containerPort: 9000
              name: p2p
          volumeMounts:
            - name: dusk-data
              mountPath: /opt/dusk
            - name: dusk-wallet
              mountPath: /home/dusk/.dusk
            - name: secrets
              mountPath: /config
              readOnly: true
          env:
            - name: PATH
              value: /opt/dusk/bin:/usr/bin:/usr/local/bin:/sbin:/bin
            - name: HOME
              value: /home/dusk
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          command: ["/opt/dusk/bin/rusk"]  # Override the default command
          args: ["-c", "/opt/dusk/conf/config.toml"]  # Specify the config file
      volumes:
        - name: dusk-data
          persistentVolumeClaim:
            claimName: dusk-data
        - name: dusk-wallet
          persistentVolumeClaim:
            claimName: dusk-wallet
        - name: secrets
          secret:
            secretName: dusk-node-secret