apiVersion: apps/v1
kind: Deployment
metadata:
  name: dusk-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dusk-node
  template:
    metadata:
      labels:
        app: dusk-node
    spec:
      securityContext:
        fsGroup: 10001  # dusk user
      containers:
        - name: dusk-node
          image: ghcr.io/mfreeman451/dusk-node:v0.0.1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: dusk-node-config
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
          volumeMounts:
            - name: dusk-secrets
              mountPath: /config
              readOnly: true
            - name: dusk-data
              mountPath: /opt/dusk
            - name: dusk-logs
              mountPath: /var/log
      volumes:
        - name: dusk-secrets
          secret:
            secretName: dusk-node-secret
        - name: dusk-data
          persistentVolumeClaim:
            claimName: dusk-node-data
        - name: dusk-logs
          emptyDir: {}
