apiVersion: apps/v1
kind: Deployment
metadata:
  name: dusk-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dusk-node
  template:
    metadata:
      labels:
        app: dusk-node
    spec:
      containers:
        - name: dusk-node
          image: ghcr.io/mfreeman451/dusk-node:v0.0.4
          imagePullPolicy: Always
          volumeMounts:
            - name: dusk-bin
              mountPath: /opt/dusk
            - name: dusk-config
              mountPath: /opt/dusk/conf
            - name: dusk-wallet-secret
              mountPath: /config
              readOnly: true
          env:
            - name: PATH
              value: /opt/dusk/bin:/usr/bin:/usr/local/bin:/sbin:/bin
      volumes:
        - name: dusk-bin
          persistentVolumeClaim:
            claimName: dusk-bin-data
        - name: dusk-config
          persistentVolumeClaim:
            claimName: dusk-config
        - name: dusk-wallet-secret
          secret:
            secretName: dusk-wallet-secret