# PersistentVolumeClaim for DUSK node data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dusk-node-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path