apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dusk-data    # For blockchain data and state
  namespace: dusk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dusk-wallet  # For wallet and config files
  namespace: dusk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path