# Secret for storing sensitive DUSK node data
apiVersion: v1
kind: Secret
metadata:
  name: dusk-node-secret
  namespace: dusk
type: Opaque
data:
  # Base64 encoded values - replace these with actual values
  mnemonic: "" # Your DUSK wallet mnemonic
  wallet-password: "" # Password for the wallet
  consensus-password: "" # Password for consensus keys
