apiVersion: v1
kind: Service
metadata:
  name: dusk-node
  namespace: dusk
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "dusk.tunnel.threadr.ai"
    metallb.universe.tf/address-pool: k3s-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - port: 8080
      targetPort: 8080
      name: api
    - port: 9000
      targetPort: 9000
      name: p2p
  selector:
    app: dusk-node